[build]
  command = "pip install -r requirements.txt"
  publish = "public"
  functions = "functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mangum"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api_server/:splat"
  status = 200

[[redirects]]
  from = "/appointments"
  to = "/.netlify/functions/api_server/appointments"
  status = 200

[[redirects]]
  from = "/services"
  to = "/.netlify/functions/api_server/services"
  status = 200
